gpus:                             null
pretrained:                       null
model: 
    name:                         UNet
    args:
        nclasses:                 13
        input_nchannels:          3
        method:                   interpolate
optimizer:
    name:                         Adam
    args:
        lr:                       0.00001
loss:
    name:                         CrossEntropyLoss
    args:
        ignore_index:             -1
metric:
    - name:                       IoU
      args:
        nclasses:                 13
        ignore_index:             -1
scheduler:
    name:                         ReduceLROnPlateau
    args:
        mode:                     min
        factor:                   0.5 
        patience:                 5 
        verbose:                  True
dataset:
    train:
        name:                     SUNRGBDDataset
        args:
            root_path:            data/SUN-RGBD
            color_img_folder:     SUNRGBD-train_images
            depth_img_folder:     sunrgbd_train_depth
            label_img_folder:     train13labels
        loader:
            batch_size:           1
            shuffle:              True
    val: 
        name:                     SUNRGBDDataset
        args:
            root_path:            data/SUN-RGBD
            color_img_folder:     SUNRGBD-test_images
            depth_img_folder:     sunrgbd_test_depth
            label_img_folder:     test13labels
        loader:
            batch_size:           1
trainer:
    nepochs:                      50
    log:
        val_step:                 1