gpus:                             null
pretrained:                       null
model: 
    name:                         UNet
    args:
        nclasses:                 2
        input_nchannels:          1
        method:                   interpolate
optimizer:
    name:                         SGD
    args:
        lr:                       0.00001
        momentum:                 0.9
        weight_decay:             0.0005
loss:
    name:                         BCEWithLogitsLoss
    args:
        # beta:                     1.2
metric:
    - name:                       IoU
      args:
        nclasses:                 2
scheduler:
    name:                         ReduceLROnPlateau
    args:
        mode:                     min
        factor:                   0.5 
        patience:                 5 
        verbose:                  True
dataset:
    train:
        name:                     IRCADSingle
        args:
            root_path:            data/3Dircadb1/train
        loader:
            batch_size:           1
            shuffle:              True
    val: 
        name:                     IRCADSingle
        args:
            root_path:            data/3Dircadb1/val
        loader:
            batch_size:           1
trainer:
    nepochs:                      50
    log:
        val_step:                 1