gpus: null
model: 
    name:                         Unet
    num_class:                    13
    method:                       interpolate
    args:
        learning_rate:            0.0001
        momentum:                 0.9
        weight_decay:             0.0005
pretrained:                       runs/2020-02-27_12:09:03/best_loss.pth

train: 
    type:                         SUNRGBD                          
    path: 
        root:                     data/SUN-RGBD
        img_folder:               SUNRGBD-train_images
        depth_folder:             sunrgbd_train_depth
        label_folder:             train13labels    
    args: 
        batch_size:               8
        epochs:                   50
        num_workers:              8
        num_iters:                10
        save_period:              10
        early_stop:               10
    log:
        val_step: 1
