gpus:                             null
pretrained:                       null
model: 
    name:                         UNet
    args:
        nclasses:                 2
        input_nchannels:          1
        method:                   interpolate
optimizer:
    name:                         Adam
    args:
        lr:                       0.000005
loss:
    name:                         FocalLoss
    args:
        # beta:                     5
        # weight:                   [0.1, 1.0]
        gamma:                    5
metric:
    - name:                       IoU
      args:
        nclasses:                 2
scheduler:
    name:                         ReduceLROnPlateau
    args:
        mode:                     min
        factor:                   0.5 
        patience:                 5
        verbose:                  True
dataset:
    train:
        name:                     IRCADSingle
        args:
            root_path:            data/3Dircadb1/train
        loader:
            batch_size:           1
            shuffle:              True
    val: 
        name:                     IRCADSingle
        args:
            root_path:            data/3Dircadb1/val
            is_train:             False
        loader:
            batch_size:           1
trainer:
    nepochs:                      50
    log:
        val_step:                 1