id: Debug
pretrained: null
model:
    name: NestedUNet
    args:
        nclasses: 2
        in_channels: 1
        first_channels: 64
        depth: 2
optimizer:
    name: Adam
    args:
        lr: 0.00001
loss:
    name: CrossEntropyLoss
    args:
        # beta: 5
        # weight: [0.1, 1.0]
        # gamma: 2
        # alpha: 0.25
metric:
    - name: MeanIoU
      args:
          nclasses: 2
    - name: PixelAccuracy
      args:
          nclasses: 2
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 5
        verbose: True
dataset:
    train:
        name: IRCADSingle
        args:
            root_path: data/3Dircadb1/test
        loader:
            batch_size: 1
            shuffle: True
    val:
        name: IRCADSingle
        args:
            root_path: data/3Dircadb1/test
            is_train: False
        loader:
            batch_size: 1
trainer:
    nepochs: 50
    log:
        val_step: 1
