gpus:                             null
pretrained:                       null
model: 
    name:                         UNet
    args:
        nclasses:                 3
        input_nchannels:          1
        method:                   interpolate
optimizer:
    name:                         Adam
    args:
        lr:                       0.00001
loss:
    name:                         CrossEntropyLoss
    args:
        # beta:                     5
        # weight:                   [1.0, 5.0]
metric:
    - name:                       IoU
      args:
        nclasses:                 3
scheduler:
    name:                         ReduceLROnPlateau
    args:
        mode:                     min
        factor:                   0.5 
        patience:                 5 
        verbose:                  True
dataset:
    train:
        name:                     LiTSSingle
        args:
            root_path:            data/LiTS/train
        loader:
            batch_size:           1
            shuffle:              True
            # pin_memory:           True
    val: 
        name:                     LiTSSingle
        args:
            root_path:            data/LiTS/val
        loader:
            batch_size:           1
trainer:
    nepochs:                      50
    log:
        val_step:                 1